version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: main
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./tasks:/app
    ports:
      - "5432:5432"
